### ISSUE TITLE
Add support for null enums

### ISSUE THREAD

**Issue by mferris26** [oas-tools/oas-tools#234]
oas-tools version: 2.1.6
openapi version: 3.0.0

**Schema**
```
{
         "nullableEnum": {
                "nullable": true,
                "enum": [
                    "1",
                    "2",
                    null
                ],
                "type": "string"
            }
}
```
**Request**
```
{
        "nullableEnum": null
}
```

**Error**
```
TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:10)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (~/node_modules/oas-tools/src/lib/utils.js:28:7)
    at Array.forEach (<anonymous>)
    at Object.fixNullable (~/node_modules/oas-tools/src/lib/utils.js:26:38)
    at checkRequestData (~/node_modules/oas-tools/src/middleware/oas-validator.js:120:15)
    at OASValidator (~/node_modules/oas-tools/src/middleware/oas-validator.js:470:5)
at OASValidator (~/node_modules/oas-tools/src/middleware/oas-validator.js:470:5)
```

As per enum specification (https://swagger.io/docs/specification/data-models/enums/), it is possible to have a nullable enum and is defined as above. Without specifying null in the enum array, it will throw an enum mismatch error.

**Comment by alesancor1** [comment]
A new release that solves this issue has been published (`v3.0.2`). Please run `npm update @oas-tools/core` to update OAS Tools core library.
