### ISSUE TITLE
[BUG] Cannot convert undefined or null to object oas param file has issue

### ISSUE THREAD

**Issue by umar4sap** [oas-tools/oas-tools#360]
## **Describe the bug**
[oas-tools] ERROR: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _getParameterValue (file:///Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/core/src/middleware/native/oas-params.js:93:36)
    at file:///Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/core/src/middleware/native/oas-params.js:27:78
    at Array.forEach (<anonymous>)
    at OASParams.<anonymous> (file:///Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/core/src/middleware/native/oas-params.js:27:35)
    at /Users/acoder/Documents/GitHub/login-service/node_modules/@oas-tools/commons/dist/middleware/base.js:42:41
    at /Users/acoder/Documents/GitHub/login-service/node_modules/dd-trace/packages/datadog-instrumentations/src/router.js:50:25
    at /Users/acoder/Documents/GitHub/login-service/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:22:21
    at Layer.handle [as handle_request] (/Users/acoder/Documents/GitHub/login-service/node_modules/express/lib/router/layer.js:95:5)

**Comment by umar4sap** [comment]
https://github.com/oas-tools/oas-tools/pull/359

**Comment by alesancor1** [comment]
Please provide further explanation of the issue and if possible, a way to reproduce the error. Try to follow the issue and PR templates.
