### ISSUE TITLE
Configure write directory?

### ISSUE THREAD

**Issue by 8enmann** [oas-tools/oas-tools#82]
Google Appengine uses a write only file except for `/tmp`, so I'm getting this error:
```
Error: EROFS: read-only file system, open '/srv/node_modules/oas-tools/swagger-ui/index.html'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at registerPaths (/srv/node_modules/oas-tools/src/index.js:358:10)
    at Object.initializeMiddleware (/srv/node_modules/oas-tools/src/index.js:409:3)
    at Object.<anonymous> (/srv/index.js:26:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```
Is there a config setting to change the directory oas-tools writes to?

**Comment by yashmurty** [comment]
@8enmann Did you manage to solve this? CC @raffrearaUS 
I am facing similar issue on AWS Lambda.

**Comment by 8enmann** [comment]
Nope don't think so :(

**Comment by oceanicsdotio** [comment]
@yashmurty @8enmann We had to disable SwaggerUI by setting docs paths to null. I always use Redoc or Stoplight instead anyway.
